# Generated by Django 6.0.3 on 2026-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('montant_total', models.FloatField()),
                ('statut', models.CharField(choices=[('payer', 'payer'), ('non_payer', 'non_payer')], default='non_payer', max_length=20)),
            ],
        ),
    ]
