# Generated by Django 6.0.3 on 2026-03-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateField()),
                ('montant_total', models.FloatField()),
                ('statut', models.CharField(choices=[('payer', 'Payer'), ('non_payer', 'Non Payer')], max_length=20)),
                ('brevet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
