# Generated by Django 6.0.2 on 2026-04-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brevets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id_paiement", models.AutoField(primary_key=True, serialize=False)),
                ("date_paiement", models.DateField()),
                ("montant_total", models.FloatField()),
                (
                    "statut",
                    models.CharField(
                        choices=[("payer", "payer"), ("non_payer", "non_payer")],
                        max_length=20,
                    ),
                ),
                (
                    "id_brevet",
                    models.ForeignKey(
                        db_column="id_brevet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brevets.brevet",
                    ),
                ),
            ],
        ),
    ]
