# Generated by Django 6.0.2 on 2026-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0003_rename_status_brevet_statut"),
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Payment",
            new_name="Paiement",
        ),
    ]
