# Generated by Django 6.0.3 on 2026-04-07 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0002_initial'),
        ('documents', '0002_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_brevet',
            field=models.OneToOneField(db_column='id_brevet', on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='id_document',
            field=models.OneToOneField(blank=True, db_column='id_document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document'),
        ),
    ]
