# Generated by Django 6.0.2 on 2026-03-25 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('paiements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='documents.documents'),
        ),
    ]
