# Generated by Django 6.0.2 on 2026-04-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0004_alter_demandebrevet_autre_info_and_more"),
        ("documents", "0004_alter_typedocument_description"),
        ("paiements", "0004_alter_paiement_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="id_document",
            field=models.ForeignKey(
                blank=True,
                db_column="id_document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.documents",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="id_brevet",
            field=models.OneToOneField(
                db_column="id_brevet",
                on_delete=django.db.models.deletion.CASCADE,
                to="brevets.brevet",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[("payer", "payer"), ("non_payer", "non_payer")],
                default="non_payer",
                max_length=20,
            ),
        ),
    ]
