# Generated by Django 6.0.3 on 2026-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('nom_document', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('taille_max', models.IntegerField()),
                ('format_autorise', models.CharField(max_length=50)),
            ],
        ),
    ]
