# Generated by Django 6.0.3 on 2026-03-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0001_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Typedocument',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('taille_max', models.IntegerField()),
                ('format_autorise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('nom_document', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='brevets/documents/')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('brevet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet')),
                ('paiement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paiements.paiement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('typedocument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.typedocument')),
            ],
        ),
    ]
