# Generated by Django 6.0.2 on 2026-04-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brevets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="typedocument",
            fields=[
                ("id_type", models.AutoField(primary_key=True, serialize=False)),
                ("nom_type", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("taille_max", models.IntegerField()),
                ("format_autorise", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                ("id_document", models.AutoField(primary_key=True, serialize=False)),
                ("nom_document", models.CharField(max_length=255)),
                ("fichier", models.CharField(max_length=255)),
                ("date_ajout", models.DateField(auto_now_add=True)),
                (
                    "id_brevet",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_brevet",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brevets.brevet",
                    ),
                ),
            ],
        ),
    ]
