# Generated by Django 6.0.2 on 2026-04-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documents",
            name="id_type",
            field=models.ForeignKey(
                db_column="id_type",
                on_delete=django.db.models.deletion.CASCADE,
                to="documents.typedocument",
            ),
        ),
    ]
