# Generated by Django 6.0.3 on 2026-04-07 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0002_initial'),
        ('documents', '0001_initial'),
        ('paiements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='id_brevet',
            field=models.ForeignKey(blank=True, db_column='id_brevet', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.brevet'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_demande',
            field=models.ForeignKey(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_paiement',
            field=models.OneToOneField(blank=True, db_column='id_paiement', null=True, on_delete=django.db.models.deletion.CASCADE, to='paiements.paiement'),
        ),
        migrations.AddField(
            model_name='document',
            name='id_type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.CASCADE, to='documents.typedocument'),
        ),
    ]
