# Generated by Django 6.0.2 on 2026-04-02 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0002_initial"),
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="id_demande",
            field=models.ForeignKey(
                blank=True,
                db_column="id_demande",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="brevets.demandebrevet",
            ),
        ),
    ]
