# Generated by Django 6.0.2 on 2026-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_documents_id_demande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typedocument",
            name="description",
            field=models.TextField(),
        ),
    ]
