# Generated by Django 6.0.2 on 2026-04-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_typedocument_description"),
        ("paiements", "0005_paiement_id_document_alter_paiement_id_brevet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documents",
            name="id_paiement",
            field=models.ForeignKey(
                blank=True,
                db_column="id_paiement",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="paiements.paiement",
            ),
        ),
        migrations.AlterField(
            model_name="documents",
            name="fichier",
            field=models.FileField(upload_to="documents/"),
        ),
    ]
