# Generated by Django 6.0.2 on 2026-04-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_documents_id_paiement_alter_documents_fichier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documents",
            options={"verbose_name": "Document", "verbose_name_plural": "Documents"},
        ),
    ]
