# Generated by Django 6.0.2 on 2026-04-02 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0007_alter_brevet_titre"),
        ("documents", "0006_alter_documents_options"),
        ("paiements", "0005_paiement_id_document_alter_paiement_id_brevet_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Documents",
            new_name="Document",
        ),
    ]
