# Generated by Django 6.0.3 on 2026-03-24 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposant',
            fields=[
                ('id_dep', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_dep', models.CharField(max_length=100)),
                ('prenom_dep', models.CharField(max_length=100)),
                ('denomination', models.CharField(max_length=255)),
                ('adresse_dep', models.TextField()),
                ('nationalite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeBrevet',
            fields=[
                ('id_demande', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=100)),
                ('num_depot', models.IntegerField()),
                ('date_depot', models.DateField()),
                ('pays_origine', models.CharField(max_length=100)),
                ('numdemande_CA', models.IntegerField()),
                ('date_CA', models.DateField()),
                ('mandataire', models.CharField(max_length=255)),
                ('date_pouvoir', models.DateField()),
                ('prepose_reception', models.CharField(max_length=255)),
                ('lieu_reception', models.CharField(max_length=255)),
                ('date_reception', models.DateField()),
                ('autre_info', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('valider', 'Valider'), ('non_valider', 'Non Valider')], default='non_valider', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deposant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brevets.deposant')),
            ],
        ),
        migrations.CreateModel(
            name='Brevet',
            fields=[
                ('id_brevet', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num_brevet', models.IntegerField()),
                ('titre', models.CharField(max_length=255)),
                ('num_depot', models.IntegerField()),
                ('date_depot', models.DateField()),
                ('date_sortie', models.DateField()),
                ('titulaire', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACCEPTER', 'Accepter'), ('REFUSER', 'Refuser'), ('EN_ATTENTE', 'En attente')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet')),
            ],
        ),
        migrations.CreateModel(
            name='Inventeur',
            fields=[
                ('id_inv', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_inv', models.CharField(max_length=100)),
                ('prenom_inv', models.CharField(max_length=100)),
                ('adresse_inv', models.TextField()),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventeurs', to='brevets.demandebrevet')),
            ],
        ),
    ]
