# Generated by Django 6.0.3 on 2026-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brevet',
            fields=[
                ('id_brevet', models.AutoField(primary_key=True, serialize=False)),
                ('num_brevet', models.IntegerField()),
                ('titre', models.CharField(max_length=1000)),
                ('num_depo', models.IntegerField()),
                ('date_depo', models.DateField()),
                ('date_sortie', models.DateField()),
                ('titulaire', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ACCEPTER', 'ACCEPTER'), ('REFUSER', 'REFUSER'), ('EN_ATTENTE', 'EN_ATTENTE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeBrevet',
            fields=[
                ('id_demande', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('nature', models.CharField(max_length=100)),
                ('num_depo', models.IntegerField()),
                ('date_depo', models.DateField()),
                ('pays_origine', models.CharField(max_length=100)),
                ('numdemande_CA', models.IntegerField()),
                ('date_CA', models.DateField()),
                ('mandataire', models.CharField(max_length=255)),
                ('date_pouvoir', models.DateField()),
                ('prepose_reception', models.CharField(max_length=255)),
                ('lieu_reception', models.CharField(max_length=255)),
                ('date_reception', models.DateField()),
                ('autre_info', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('valider', 'valider'), ('non_valider', 'non_valider')], default='non_valider', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deposant',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('nom_dep', models.CharField(max_length=100)),
                ('prenom_dep', models.CharField(max_length=100)),
                ('denomination', models.CharField(max_length=255)),
                ('adresse_dep', models.CharField(max_length=255)),
                ('nationalite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventeur',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('nom_inv', models.CharField(max_length=100)),
                ('prenom_inv', models.CharField(max_length=100)),
                ('adress_inv', models.CharField(max_length=255)),
            ],
        ),
    ]
