# Generated by Django 6.0.3 on 2026-04-07 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brevet',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='brevets_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandebrevet',
            name='id',
            field=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brevet',
            name='id_demande',
            field=models.OneToOneField(blank=True, db_column='id_demande', null=True, on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.AddField(
            model_name='deposant',
            name='id_demande',
            field=models.ForeignKey(db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.AddField(
            model_name='inventeur',
            name='id_demande',
            field=models.ManyToManyField(related_name='inventeurs', to='brevets.demandebrevet'),
        ),
    ]
