# Generated by Django 6.0.2 on 2026-03-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandebrevet',
            name='titre',
            field=models.CharField(max_length=1000),
        ),
    ]
