# Generated by Django 6.0.2 on 2026-04-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brevet",
            old_name="status",
            new_name="statut",
        ),
    ]
