# Generated by Django 6.0.2 on 2026-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0003_rename_status_brevet_statut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandebrevet",
            name="autre_info",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="demandebrevet",
            name="titre",
            field=models.TextField(),
        ),
    ]
