# Generated by Django 6.0.2 on 2026-04-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0005_alter_deposant_id_demande_alter_inventeur_id_demande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposant",
            name="id_demande",
            field=models.OneToOneField(
                db_column="id_demande",
                on_delete=django.db.models.deletion.CASCADE,
                to="brevets.demandebrevet",
            ),
        ),
        migrations.AlterField(
            model_name="inventeur",
            name="id_demande",
            field=models.ForeignKey(
                db_column="id_demande",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventeurs",
                to="brevets.demandebrevet",
            ),
        ),
    ]
