# Generated by Django 6.0.2 on 2026-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brevets", "0006_alter_deposant_id_demande_alter_inventeur_id_demande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brevet",
            name="titre",
            field=models.CharField(max_length=1000),
        ),
    ]
