# Generated by Django 6.0.3 on 2026-04-06 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brevets', '0007_alter_brevet_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposant',
            name='id_demande',
            field=models.ForeignKey(db_column='id_demande', on_delete=django.db.models.deletion.CASCADE, to='brevets.demandebrevet'),
        ),
        migrations.RemoveField(
            model_name='inventeur',
            name='id_demande',
        ),
        migrations.AddField(
            model_name='inventeur',
            name='id_demande',
            field=models.ManyToManyField(related_name='inventeurs', to='brevets.demandebrevet'),
        ),
    ]
