# Generated by Django 6.0.3 on 2026-04-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='test_force',
        ),
    ]
