# Generated by Django 6.0.2 on 2026-04-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_utilisateur_id_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="id_role",
            field=models.ForeignKey(
                db_column="id_role",
                on_delete=django.db.models.deletion.PROTECT,
                to="users.role",
            ),
        ),
    ]
