# Generated by Django 6.0.3 on 2026-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_role_test_force'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='date_ajout',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
