# Generated by Django 6.0.3 on 2026-03-24 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brevets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id_recours', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TRAITE', 'Traité'), ('REFUSE', 'Refusé')], default='EN_COURS', max_length=20)),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('brevet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours_associes', to='brevets.brevet')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recours_faits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recours',
                'verbose_name_plural': 'Recours',
            },
        ),
    ]
