# Generated by Django 6.0.3 on 2026-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recours',
            fields=[
                ('id_recours', models.AutoField(primary_key=True, serialize=False)),
                ('date_depot', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('EN_COURS', 'EN_COURS'), ('TRAITE', 'TRAITE'), ('REFUSE', 'REFUSE')], default='EN_COURS', max_length=20)),
                ('date_traitement', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
