# Generated by Django 6.0.2 on 2026-04-01 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brevets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recours",
            fields=[
                ("Id_recours", models.AutoField(primary_key=True, serialize=False)),
                ("date_depot", models.DateField()),
                ("motif", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "EN_COURS"),
                            ("TRAITE", "TRAITE"),
                            ("REFUSE", "REFUSE"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                ("date_traitement", models.DateField(blank=True, null=True)),
                (
                    "id_brevet",
                    models.ForeignKey(
                        db_column="id_brevet",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brevets.brevet",
                    ),
                ),
            ],
        ),
    ]
