# Generated by Django 6.0.2 on 2026-04-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recours", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recours",
            old_name="Id_recours",
            new_name="id_recours",
        ),
    ]
