# Generated by Django 6.0.2 on 2026-04-02 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recours", "0002_rename_id_recours_recours_id_recours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recours",
            name="id_user",
            field=models.ForeignKey(
                db_column="id_user",
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recours",
            name="date_depot",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="recours",
            name="description",
            field=models.TextField(),
        ),
    ]
