# Generated by Django 6.0.2 on 2026-04-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id_notif",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("date_notif", models.DateTimeField(auto_now_add=True)),
                ("message", models.CharField(max_length=1000)),
                ("etat", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_notif"],
            },
        ),
    ]
