# Generated by Django 6.0.3 on 2026-03-24 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_notif', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('etat', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_notif'],
            },
        ),
    ]
