# Generated by Django 6.0.3 on 2026-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('date_notif', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('etat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_notif'],
            },
        ),
    ]
