# Generated by Django 6.0.2 on 2026-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="message",
            field=models.TextField(),
        ),
    ]
